Dockerised the nextapp
zeul22/SASS_Form_Builder pull request #16
Opened 2024-06-30 09:38 UTC by Avijit2002

Use "docker build . -t image_name" to build the image.
Use "docker run --env-file <env_file_name> -p 3000:3000 -d <imageName>" to run the image.

2024-07-01 06:14 UTC, zeul22 commented
Hi, the code seems a little off as we have not used 'src/' directory. Also would you be able to set up env-variables using docker-compose that takes values from .env file?

2024-07-01 06:16 UTC, zeul22 commented on DockerFile
Please modify the WorkDIR and add env variables referenced from docker-compose

2024-07-01 07:41 UTC, Avijit2002 commented on DockerFile
okk sure

2024-07-01 08:10 UTC, Avijit2002 commented
Added compose.yml file and fixed the working directory path.

2024-07-01 13:25 UTC, zeul22 requested changes

2024-07-01 13:25 UTC, zeul22 commented on compose.yml
Please rename the file as 'docker-compose.yml'

2024-07-01 13:56 UTC, Avijit2002 commented on compose.yml
okk

2024-07-01 13:59 UTC, Avijit2002 commented
compose.yml file renamed as 'docker-compose.yml.

2024-07-01 15:03 UTC, Avijit2002 commented on compose.yml
Done

2024-07-01 15:29 UTC, merged

2024-07-01 15:29 UTC, zeul22 commented
Thank you Avijit for the contribution, there are other issues as well if you are interested!

2024-07-02 18:20 UTC, Avijit2002 commented
Thank you @zeul22 for merging my PR. Will surely contribute more to this project.